from enum import IntEnum

from _tobii_stream_engine_cffi import lib as _lib


class Capability(IntEnum):
    DISPLAY_AREA_WRITABLE = _lib.TOBII_CAPABILITY_DISPLAY_AREA_WRITABLE
    CALIBRATION_2D = _lib.TOBII_CAPABILITY_CALIBRATION_2D
    CALIBRATION_3D = _lib.TOBII_CAPABILITY_CALIBRATION_3D
    PERSISTENT_STORAGE = _lib.TOBII_CAPABILITY_PERSISTENT_STORAGE
    CALIBRATION_PER_EYE = _lib.TOBII_CAPABILITY_CALIBRATION_PER_EYE
    COMPOUND_STREAM_WEARABLE_3D_GAZE_COMBINED = (
        _lib.TOBII_CAPABILITY_COMPOUND_STREAM_WEARABLE_3D_GAZE_COMBINED
    )
    FACE_TYPE = _lib.TOBII_CAPABILITY_FACE_TYPE
    COMPOUND_STREAM_USER_POSITION_GUIDE_XY = (
        _lib.TOBII_CAPABILITY_COMPOUND_STREAM_USER_POSITION_GUIDE_XY
    )
    COMPOUND_STREAM_USER_POSITION_GUIDE_Z = (
        _lib.TOBII_CAPABILITY_COMPOUND_STREAM_USER_POSITION_GUIDE_Z
    )
    COMPOUND_STREAM_WEARABLE_LIMITED_IMAGE = (
        _lib.TOBII_CAPABILITY_COMPOUND_STREAM_WEARABLE_LIMITED_IMAGE
    )
    COMPOUND_STREAM_WEARABLE_PUPIL_DIAMETER = (
        _lib.TOBII_CAPABILITY_COMPOUND_STREAM_WEARABLE_PUPIL_DIAMETER
    )
    COMPOUND_STREAM_WEARABLE_PUPIL_POSITION = (
        _lib.TOBII_CAPABILITY_COMPOUND_STREAM_WEARABLE_PUPIL_POSITION
    )
    COMPOUND_STREAM_WEARABLE_EYE_OPENNESS = (
        _lib.TOBII_CAPABILITY_COMPOUND_STREAM_WEARABLE_EYE_OPENNESS
    )
    COMPOUND_STREAM_WEARABLE_3D_GAZE_PER_EYE = (
        _lib.TOBII_CAPABILITY_COMPOUND_STREAM_WEARABLE_3D_GAZE_PER_EYE
    )
    COMPOUND_STREAM_WEARABLE_USER_POSITION_GUIDE_XY = (
        _lib.TOBII_CAPABILITY_COMPOUND_STREAM_WEARABLE_USER_POSITION_GUIDE_XY
    )
    COMPOUND_STREAM_WEARABLE_TRACKING_IMPROVEMENTS = (
        _lib.TOBII_CAPABILITY_COMPOUND_STREAM_WEARABLE_TRACKING_IMPROVEMENTS
    )
    COMPOUND_STREAM_WEARABLE_CONVERGENCE_DISTANCE = (
        _lib.TOBII_CAPABILITY_COMPOUND_STREAM_WEARABLE_CONVERGENCE_DISTANCE
    )
    COMPOUND_STREAM_WEARABLE_IMPROVE_USER_POSITION_HMD = (
        _lib.TOBII_CAPABILITY_COMPOUND_STREAM_WEARABLE_IMPROVE_USER_POSITION_HMD
    )
    COMPOUND_STREAM_WEARABLE_INCREASE_EYE_RELIEF = (
        _lib.TOBII_CAPABILITY_COMPOUND_STREAM_WEARABLE_INCREASE_EYE_RELIEF
    )
