from enum import IntEnum

from _tobii_stream_engine_cffi import lib as _lib


class Stream(IntEnum):
    GAZE_POINT = _lib.TOBII_STREAM_GAZE_POINT
    GAZE_ORIGIN = _lib.TOBII_STREAM_GAZE_ORIGIN
    EYE_POSITION_NORMALIZED = _lib.TOBII_STREAM_EYE_POSITION_NORMALIZED
    USER_PRESENCE = _lib.TOBII_STREAM_USER_PRESENCE
    HEAD_POSE = _lib.TOBII_STREAM_HEAD_POSE
    WEARABLE = _lib.TOBII_STREAM_WEARABLE
    GAZE_DATA = _lib.TOBII_STREAM_GAZE_DATA
    DIGITAL_SYNCPORT = _lib.TOBII_STREAM_DIGITAL_SYNCPORT
    DIAGNOSTICS_IMAGE = _lib.TOBII_STREAM_DIAGNOSTICS_IMAGE
    CUSTOM = _lib.TOBII_STREAM_CUSTOM
